config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  get '/profile', to:'users#profile'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  resources :users, only: %i[new create edit update show]
  resources :sessions, only: %i[new create destroy]
  resources :items
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  validates :bio, length: { minimum: 50, maximum: 200 }, on: :update
  validates :email, presence: true, uniqueness: true
  VALID_PASSWORD_REGEX = /[a-z]\d/i
  validates :password, length: { minimum: 8 }, allow_nil: true,
            format: { with: VALID_PASSWORD_REGEX, message: "は英数字を含めてください。" }

  has_one_attached :avatar
  has_many :items, dependent: :destroy

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def learning_data(month)
    learning_data = self.items.where(created_at: month.beginning_of_month..month.end_of_month)
    return learning_data
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]= "こんにちは#{@user}さん！"
      log_in @user
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @user = current_user

    @backend_2months_ago = Item.where(
                                created_at: Time.current.months_ago(2).beginning_of_month..Time.current.months_ago(2).end_of_month,
                                category_id: 1, user_id: current_user.id).pluck(:learning_time).sum
    @backend_last_month = Item.where(
                                created_at: Time.current.months_ago(1).beginning_of_month..Time.current.months_ago(1).end_of_month,
                                category_id: 1, user_id: current_user.id).pluck(:learning_time).sum
    @backend_this_month = Item.where(
                                created_at: Time.current.beginning_of_month..Time.current.end_of_month,
                                category_id: 1, user_id: current_user.id).pluck(:learning_time).sum

    @frontend_2months_ago = Item.where(
                                created_at: Time.current.months_ago(2).beginning_of_month..Time.current.months_ago(2).end_of_month,
                                category_id: 2, user_id: current_user.id).pluck(:learning_time).sum
    @frontend_last_month = Item.where(
                                created_at: Time.current.months_ago(1).beginning_of_month..Time.current.months_ago(1).end_of_month,
                                category_id: 2, user_id: current_user.id).pluck(:learning_time).sum
    @frontend_this_month = Item.where(
                                created_at: Time.current.beginning_of_month..Time.current.end_of_month,
                                category_id: 2, user_id: current_user.id).pluck(:learning_time).sum

    @infra_2months_ago = Item.where(
                                created_at: Time.current.months_ago(2).beginning_of_month..Time.current.months_ago(2).end_of_month,
                                category_id: 3, user_id: current_user.id).pluck(:learning_time).sum
    @infra_last_month = Item.where(
                                created_at: Time.current.months_ago(1).beginning_of_month..Time.current.months_ago(1).end_of_month,
                                category_id: 3, user_id: current_user.id).pluck(:learning_time).sum
    @infra_this_month = Item.where(
                                created_at: Time.current.beginning_of_month..Time.current.end_of_month,
                                category_id: 3, user_id: current_user.id).pluck(:learning_time).sum
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :bio, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>自己紹介を編集する</h1>

<%= form_with(model: @user, class: 'profile-edit') do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  <%= f.label :bio, "自己紹介文" %>
  <%= f.text_area :bio, class: 'form-control' %>
  <small>50文字以上、200文字未満で入力してください</small><br>

  <%= f.label :avatar, "アバター画像" %>
  <%= f.label :avatar, "画像ファイルを添付する", class: 'avatar-btn' %>
  <%= f.file_field :avatar, class: 'avatar-input', accept: "image/jpeg,image/gif,image/png" %>

  <%= f.submit "自己紹介を確定する", class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "登録する", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="users-profile">
  <div class="avatar">
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar %>
    <% else %>
      <div class="avatar-placeholder"></div>
    <% end %>
  </div>
  <div class="bio">
    <h3>自己紹介</h3>
    <%= simple_format(@user.bio, sanitize: true, class: 'self_introduction') %>
    <%= button_to '自己紹介を編集する', edit_user_path(@user), method: :get, class: 'btn btn-primary' %>
  </div>
</div>

<div class="learning-chart">
  <h3 class="chart-title">学習チャート</h3>

  <%= button_to '編集する', items_path, method: :get, class: 'btn btn-primary chart-edit-btn' %>

  <div class="chart">
    <canvas id="myChart" style="display: block; box-sizing: border-box; height: 500px; width: 1064px; margin: 0 auto;"></canvas>
  </div>

  <script>
    const ctx = document.getElementById('myChart');

    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['先々月', '先月', '今月'],
        datasets: [{
          label: 'バックエンド',
          data: [<%= @backend_2months_ago %>, <%= @backend_last_month %>, <%= @backend_this_month %>],
          borderWidth: 1
        },
        {
          label: 'フロントエンド',
          data: [<%= @frontend_2months_ago %>, <%= @frontend_last_month %>, <%= @frontend_this_month %>],
          borderWidth: 1
        },
        {
          label: 'インフラ',
          data: [<%= @infra_2months_ago %>, <%= @infra_last_month %>, <%= @infra_this_month %>],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true,
            suggestedMax: 100
          }
        }
      }
    });

  </script>
</div>