config/routes.rb
Rails.application.routes.draw do
  root 'users#show'
  get '/profile', to:'users#profile'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy'

  resources :users, only: %i[new create edit update show]
  resources :sessions, only: %i[new create destroy]
  resources :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :learning_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user

  def index
    @months_options = [
      ["#{Date.today.month}月", Date.today.month],
      ["#{Date.today.months_ago(1).month}月", Date.today.months_ago(1).month],
      ["#{Date.today.months_ago(2).month}月", Date.today.months_ago(2).month]
    ]

    case params[:selected_value]
    when Time.current.month.to_s
      @items = current_user.learning_data(Time.current)
    when Time.current.months_ago(1).month.to_s
      @items = current_user.learning_data(Time.current.months_ago(1))
    when Time.current.months_ago(2).month.to_s
      @items = current_user.learning_data(Time.current.months_ago(2))
    else
      @items = current_user.learning_data(Time.current)
    end
  end

  def new
    query = get_referer_query
    month = if query["selected_value"][0]
              query["selected_value"][0].to_i
            else
              Time.current.month
            end
    category = Category.find(params[:category_id])
    @item = category.items.build(created_at: Time.current.change(month: month))
    @selected_value = month
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      message = "#{@item.category.name}に#{@item.name}を\n#{@item.learning_time}分で追加しました！"
      redirect_to items_path(selected_value: params[:selected_value]), flash: { success: message }, status: :found
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to determine_redirect_path, flash: { success: "#{@item.name}の学習時間を保存しました。" }, status: :found
    else
      redirect_to determine_redirect_path, flash: { danger: "学習記録に失敗しました。" }, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to determine_redirect_path, flash: { success: "#{@item.name}を削除しました!" }, status: :see_other 
  end

  private

    def item_params
      params.require(:item).permit(:name, :learning_time, :category_id, :created_at).merge(user_id: current_user.id)
    end

    def get_referer_query
      uri = URI.parse(request.referer)
      query = CGI.parse(uri.query) if uri.query
    end

    def determine_redirect_path
      query = get_referer_query
      path = query.nil? ? items_path : items_path(selected_value: query["selected_value"][0])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<section id="modal" class="modal">
  <div class="modalBg">
    <div class="modalWrapper">
      <div class="modalContents">
        <%= simple_format(flash[:success]) %>
      </div>
      <div id="modalClose" class="modalClose">
        <button>スキル編集ページに戻る</button>
      </div>
    </div>
  </div>
</section>

<div class="wrapper">
  <%= render 'shared/flash' unless flash[:success] %>
  <%= select_tag 'custom_select', options_for_select(@months_options) %>

  <% Category.all.each do |category| %>
  <div class="category">
    <div class="title">
      <p><%= category.name %></p>
      <div class="new-item-link">
        <%= link_to '項目を追加する', new_item_path(category_id: category.id) %>
      </div>
    </div>
    <div class="skill-table">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" class="item_name">項目名</th>
            <th scope="col" class="">学習時間</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @items.select{|item| item.category.name == category.name}.each do |item| %>
            <tr>
              <td><%= item.name %></td>
              <%= form_with(model: item, local: true) do |f| %>
                <td style="padding: 16px;"><%= f.number_field :learning_time %></td>
                <td style="padding: 16px; vertical-align: middle;"><%= f.submit '学習時間を保存する', class: 'submit-btn' %></td>
              <% end %>
              <td style="padding: 16px 40px 16px 16px; vertical-align: middle;">
                <%= button_to "削除する", item_path(item), method: :delete, confirm: "本当に削除しますか？", class: 'delete-btn' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <% end %>
</div>

app/views/items/new.html.erb
<h1><%= @item.category.name %>に項目を追加</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @item) do |f| %>
      <%= render 'shared/error_messages', object: @item %>
      <%= f.hidden_field :category_id, value: @item.category.id %>
      <%= f.hidden_field :created_at, value: @item.created_at %>
      <%= hidden_field_tag :selected_value, @selected_value %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :learning_time %>
      <%= f.number_field :learning_time, class: 'form-control' %>

      <%= f.submit "追加する", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>